# Generated by Django 5.0.7 on 2024-07-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_rename_pageurl_food_largeimageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
