# Generated by Django 5.0.7 on 2024-07-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_alter_food_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='userImageURL',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
